padding: 1
end: 
divider: 
lines_above: 1
modules:
- type: exitcode
  show_success: true
  success_output: 
  success_fg: "#ffffff"
  success_bg: "#000000"
  failure_fg: "#ffffff"
  failure_bg: "#bb4444"
- type: cwd
  label: " %s"
  max_depth: 3
  fg: "#aaaaaa"
  bg: "#334488"
- type: git
  fg: "#777777"
  bg: "#393939"
